FROM maven:3-jdk-11-slim
COPY . /opt
RUN cd /opt && mvn clean package -DskipTests=true -Dmaven.repo.local=/opt/.m2/repository
CMD ["java", "-jar", "/opt/target/spring-petclinic-rest-2.1.5.jar", "--spring.profiles.active=mysql,spring-data-jpa", "--spring.datasource.url=jdbc:mysql://petclinic-db.mysql.database.azure.com:3306/petclinic?serverTimezone=UTC","--server.port=80"]