FROM openjdk:11-slim
COPY ./target/spring-petclinic-rest-2.1.5.jar /opt/spring-petclinic-rest-2.1.5.jar
CMD ["java", "-jar", "/opt/spring-petclinic-rest-2.1.5.jar", "--spring.profiles.active=mysql,spring-data-jpa", "--spring.datasource.url=jdbc:mysql://petclinic-db.mysql.database.azure.com:3306/petclinic?serverTimezone=UTC","--server.port=80"]